[package]
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
name = "chapter-nine"
version = "0.1.0"
[dependencies]
futures = "0.1.18"
hyper = "0.11.21"
reqwest = "0.8.5"
serde = "1.0.30"
serde_derive = "1.0.30"
